#!/usr/bin/python2.7 -OO
# EASY-INSTALL-ENTRY-SCRIPT: 'Tasty==0.1.4','console_scripts','tasty'
__requires__ = 'Tasty==0.1.4'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Tasty==0.1.4', 'console_scripts', 'tasty')()
    )
